[package]
name = "lupe-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
# Discord API
serenity = { version = "0.12", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
    "framework",
    "standard_framework"
] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

# HTTP client for API calls
reqwest = { version = "0.11", features = ["json"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Configuration
dotenvy = "0.15"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utilities
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"

# Time handling
chrono = { version = "0.4", features = ["serde"] }
time = { version = "0.3", features = ["macros", "formatting"] }

# Caching (optional)
dashmap = "5.5"